# 线上配置文件
# wsy
server:
  port: 8101
spring:
  # 数据库配置
  # todo 需替换配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.105.202.52:3306/simpleapi
    username: simpleapi_user
    password: 0705Wsymynpy_
  # Redis 配置
  # todo 需替换配置
  redis:
    database: 1
    host: 39.105.202.52
    port: 6379
    timeout: 5000
    password: 12345678
mybatis-plus:
  configuration:
    # 生产环境关闭日志
    log-impl: ''
# 接口文档配置
knife4j:
  basic:
    enable: true
    username: root
    password: 123456
