server:
  port: 8090
spring:
  cloud:
    gateway:
      routes:
        - id: simpleapi_route
          uri: http://localhost:8123
          predicates:
            - Path=/api/**

logging:
  level:
    org:
      springframework:
        cloud:
          gateway: trace

#dubbo配置
dubbo:
  application:
    name: dubbo-springboot-demo-provider
  protocol:
    name: dubbo
    port: 22223
  registry:
    id: nacos-registry
    address: nacos://localhost:8848


